//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.SVC_AutomatonsBasicLists {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionTokenWcfHeader", Namespace="http://accipiens.com/Common")]
    [System.SerializableAttribute()]
    public partial class SessionTokenWcfHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CallerApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.SVC_AutomatonsBasicLists.MethodSoapHeaderInfo CallerMethodInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DelegateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTraceOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ConsoleApp1.SVC_AutomatonsBasicLists.LogLevel> TraceLogLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UiCultureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CallerApplicationId {
            get {
                return this.CallerApplicationIdField;
            }
            set {
                if ((this.CallerApplicationIdField.Equals(value) != true)) {
                    this.CallerApplicationIdField = value;
                    this.RaisePropertyChanged("CallerApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.SVC_AutomatonsBasicLists.MethodSoapHeaderInfo CallerMethodInfo {
            get {
                return this.CallerMethodInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerMethodInfoField, value) != true)) {
                    this.CallerMethodInfoField = value;
                    this.RaisePropertyChanged("CallerMethodInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Culture {
            get {
                return this.CultureField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureField, value) != true)) {
                    this.CultureField = value;
                    this.RaisePropertyChanged("Culture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DelegateUserId {
            get {
                return this.DelegateUserIdField;
            }
            set {
                if ((this.DelegateUserIdField.Equals(value) != true)) {
                    this.DelegateUserIdField = value;
                    this.RaisePropertyChanged("DelegateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostAddress {
            get {
                return this.HostAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HostAddressField, value) != true)) {
                    this.HostAddressField = value;
                    this.RaisePropertyChanged("HostAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostName {
            get {
                return this.HostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNameField, value) != true)) {
                    this.HostNameField = value;
                    this.RaisePropertyChanged("HostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTraceOn {
            get {
                return this.IsTraceOnField;
            }
            set {
                if ((this.IsTraceOnField.Equals(value) != true)) {
                    this.IsTraceOnField = value;
                    this.RaisePropertyChanged("IsTraceOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ConsoleApp1.SVC_AutomatonsBasicLists.LogLevel> TraceLogLevel {
            get {
                return this.TraceLogLevelField;
            }
            set {
                if ((this.TraceLogLevelField.Equals(value) != true)) {
                    this.TraceLogLevelField = value;
                    this.RaisePropertyChanged("TraceLogLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UiCulture {
            get {
                return this.UiCultureField;
            }
            set {
                if ((object.ReferenceEquals(this.UiCultureField, value) != true)) {
                    this.UiCultureField = value;
                    this.RaisePropertyChanged("UiCulture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodSoapHeaderInfo", Namespace="http://accipiens.com/Common")]
    [System.SerializableAttribute()]
    public partial class MethodSoapHeaderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CallerAplScreenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallerUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CallerAplScreenId {
            get {
                return this.CallerAplScreenIdField;
            }
            set {
                if ((this.CallerAplScreenIdField.Equals(value) != true)) {
                    this.CallerAplScreenIdField = value;
                    this.RaisePropertyChanged("CallerAplScreenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerUrl {
            get {
                return this.CallerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerUrlField, value) != true)) {
                    this.CallerUrlField = value;
                    this.RaisePropertyChanged("CallerUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogLevel", Namespace="http://schemas.datacontract.org/2004/07/Olissipo.Utils")]
    public enum LogLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoLevel = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMERGENCY = 120000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FATAL = 110000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALERT = 100000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRITICAL = 90000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEVERE = 80000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 70000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WARN = 60000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTICE = 50000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INFO = 40000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINE = 30000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEBUG = 30000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINER = 20000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRACE = 20000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINEST = 10000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VERBOSE = 10000,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomatonsForeignDataListId", Namespace="http://schemas.datacontract.org/2004/07/Olissipo.Automatons.Facade")]
    public enum AutomatonsForeignDataListId : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Automaton = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalState = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Condition = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Action = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reason = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserState = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutState = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutStateByAutUserState = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReasonByTransition = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutStateByAutomatonId = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutTransitionsByInitialAutState = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeAbbreviation", Namespace="http://accipiens.com/Common")]
    [System.SerializableAttribute()]
    public partial class CodeAbbreviation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbbreviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FetchLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InvalidDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInvalidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.SVC_AutomatonsBasicLists.PermissionFlags PermissionFlagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abbreviation {
            get {
                return this.AbbreviationField;
            }
            set {
                if ((object.ReferenceEquals(this.AbbreviationField, value) != true)) {
                    this.AbbreviationField = value;
                    this.RaisePropertyChanged("Abbreviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FetchLevel {
            get {
                return this.FetchLevelField;
            }
            set {
                if ((this.FetchLevelField.Equals(value) != true)) {
                    this.FetchLevelField = value;
                    this.RaisePropertyChanged("FetchLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvalidDate {
            get {
                return this.InvalidDateField;
            }
            set {
                if ((this.InvalidDateField.Equals(value) != true)) {
                    this.InvalidDateField = value;
                    this.RaisePropertyChanged("InvalidDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInvalid {
            get {
                return this.IsInvalidField;
            }
            set {
                if ((this.IsInvalidField.Equals(value) != true)) {
                    this.IsInvalidField = value;
                    this.RaisePropertyChanged("IsInvalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.SVC_AutomatonsBasicLists.PermissionFlags PermissionFlags {
            get {
                return this.PermissionFlagsField;
            }
            set {
                if ((this.PermissionFlagsField.Equals(value) != true)) {
                    this.PermissionFlagsField = value;
                    this.RaisePropertyChanged("PermissionFlags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionFlags", Namespace="http://accipiens.com/Common")]
    public enum PermissionFlags : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanRead = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanCreate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanModify = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanDelete = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanExecute = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanModifyTableData = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcpDetail", Namespace="http://accipiens.com/Common")]
    [System.SerializableAttribute()]
    public partial class AcpDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.SVC_AutomatonsBasicLists.BusinessError[] ErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.SVC_AutomatonsBasicLists.ExceptionKind KindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageAllField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageAllWithTechField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToStringDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.SVC_AutomatonsBasicLists.BusinessError[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.SVC_AutomatonsBasicLists.ExceptionKind Kind {
            get {
                return this.KindField;
            }
            set {
                if ((this.KindField.Equals(value) != true)) {
                    this.KindField = value;
                    this.RaisePropertyChanged("Kind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Machine {
            get {
                return this.MachineField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineField, value) != true)) {
                    this.MachineField = value;
                    this.RaisePropertyChanged("Machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageAll {
            get {
                return this.MessageAllField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageAllField, value) != true)) {
                    this.MessageAllField = value;
                    this.RaisePropertyChanged("MessageAll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageAllWithTech {
            get {
                return this.MessageAllWithTechField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageAllWithTechField, value) != true)) {
                    this.MessageAllWithTechField = value;
                    this.RaisePropertyChanged("MessageAllWithTech");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName {
            get {
                return this.OperationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationNameField, value) != true)) {
                    this.OperationNameField = value;
                    this.RaisePropertyChanged("OperationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerFolder {
            get {
                return this.ServerFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerFolderField, value) != true)) {
                    this.ServerFolderField = value;
                    this.RaisePropertyChanged("ServerFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerVersion {
            get {
                return this.ServerVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerVersionField, value) != true)) {
                    this.ServerVersionField = value;
                    this.RaisePropertyChanged("ServerVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToStringDetails {
            get {
                return this.ToStringDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ToStringDetailsField, value) != true)) {
                    this.ToStringDetailsField = value;
                    this.RaisePropertyChanged("ToStringDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessError", Namespace="http://accipiens.com/Common")]
    [System.SerializableAttribute()]
    public partial class BusinessError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HideResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RelatedAplTableIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RelatedIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.SVC_AutomatonsBasicLists.ValidationResultCode ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RscCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RscEnumTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo {
            get {
                return this.ExtraInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraInfoField, value) != true)) {
                    this.ExtraInfoField = value;
                    this.RaisePropertyChanged("ExtraInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Field {
            get {
                return this.FieldField;
            }
            set {
                if ((this.FieldField.Equals(value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HideResultCode {
            get {
                return this.HideResultCodeField;
            }
            set {
                if ((this.HideResultCodeField.Equals(value) != true)) {
                    this.HideResultCodeField = value;
                    this.RaisePropertyChanged("HideResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordIndex {
            get {
                return this.RecordIndexField;
            }
            set {
                if ((this.RecordIndexField.Equals(value) != true)) {
                    this.RecordIndexField = value;
                    this.RaisePropertyChanged("RecordIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RelatedAplTableId {
            get {
                return this.RelatedAplTableIdField;
            }
            set {
                if ((this.RelatedAplTableIdField.Equals(value) != true)) {
                    this.RelatedAplTableIdField = value;
                    this.RaisePropertyChanged("RelatedAplTableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RelatedId {
            get {
                return this.RelatedIdField;
            }
            set {
                if ((this.RelatedIdField.Equals(value) != true)) {
                    this.RelatedIdField = value;
                    this.RaisePropertyChanged("RelatedId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedUrl {
            get {
                return this.RelatedUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedUrlField, value) != true)) {
                    this.RelatedUrlField = value;
                    this.RaisePropertyChanged("RelatedUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.SVC_AutomatonsBasicLists.ValidationResultCode Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RscCode {
            get {
                return this.RscCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RscCodeField, value) != true)) {
                    this.RscCodeField = value;
                    this.RaisePropertyChanged("RscCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RscEnumTypeName {
            get {
                return this.RscEnumTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RscEnumTypeNameField, value) != true)) {
                    this.RscEnumTypeNameField = value;
                    this.RaisePropertyChanged("RscEnumTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechMsg {
            get {
                return this.TechMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.TechMsgField, value) != true)) {
                    this.TechMsgField = value;
                    this.RaisePropertyChanged("TechMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Translated {
            get {
                return this.TranslatedField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslatedField, value) != true)) {
                    this.TranslatedField = value;
                    this.RaisePropertyChanged("Translated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionKind", Namespace="http://accipiens.com/Common")]
    public enum ExceptionKind : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Business = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Technical = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResultCode", Namespace="http://accipiens.com/Common")]
    public enum ValidationResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomatonsDataListId", Namespace="http://schemas.datacontract.org/2004/07/Olissipo.Automatons.Facade")]
    public enum AutomatonsDataListId : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutContext = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConditionType = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReasonValidationType = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutPostTransitionType = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicList", Namespace="http://accipiens.com/Common")]
    [System.SerializableAttribute()]
    public partial class BasicList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CleanInvalidElementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.SVC_AutomatonsBasicLists.CodeAbbreviation[] ListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CleanInvalidElement {
            get {
                return this.CleanInvalidElementField;
            }
            set {
                if ((this.CleanInvalidElementField.Equals(value) != true)) {
                    this.CleanInvalidElementField = value;
                    this.RaisePropertyChanged("CleanInvalidElement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.SVC_AutomatonsBasicLists.CodeAbbreviation[] List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomatonInternalCodeKind", Namespace="http://schemas.datacontract.org/2004/07/Olissipo.Automatons.Decoder")]
    public enum AutomatonInternalCodeKind : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Context = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalState = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentContext = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://accipiens.com", ConfigurationName="SVC_AutomatonsBasicLists.AutomatonsBasicLists")]
    public interface AutomatonsBasicLists {
        
        // CODEGEN: Generating message contract since message GetDataWithForeignRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetDataWithForeign", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetDataWithForeignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.SVC_AutomatonsBasicLists.AcpDetail), Action="http://accipiens.com/AcpDetailError", Name="AcpDetail", Namespace="http://accipiens.com/Common")]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignResponse GetDataWithForeign(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetDataWithForeign", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetDataWithForeignResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignResponse> GetDataWithForeignAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest request);
        
        // CODEGEN: Generating message contract since message GetDataListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetDataListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.SVC_AutomatonsBasicLists.AcpDetail), Action="http://accipiens.com/AcpDetailError", Name="AcpDetail", Namespace="http://accipiens.com/Common")]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListResponse GetDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetDataListResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListResponse> GetDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest request);
        
        // CODEGEN: Generating message contract since message GetForeignDataListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetForeignDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetForeignDataListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.SVC_AutomatonsBasicLists.AcpDetail), Action="http://accipiens.com/AcpDetailError", Name="AcpDetail", Namespace="http://accipiens.com/Common")]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListResponse GetForeignDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetForeignDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetForeignDataListResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListResponse> GetForeignDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest request);
        
        // CODEGEN: Generating message contract since message GetAutomatonInternalCodeDataListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutomatonInternalCodeDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutomatonInternalCodeDataListRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.SVC_AutomatonsBasicLists.AcpDetail), Action="http://accipiens.com/AcpDetailError", Name="AcpDetail", Namespace="http://accipiens.com/Common")]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListResponse GetAutomatonInternalCodeDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutomatonInternalCodeDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutomatonInternalCodeDataListRespons" +
            "e")]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListResponse> GetAutomatonInternalCodeDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest request);
        
        // CODEGEN: Generating message contract since message GetAutomatonReasonDataListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutomatonReasonDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutomatonReasonDataListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.SVC_AutomatonsBasicLists.AcpDetail), Action="http://accipiens.com/AcpDetailError", Name="AcpDetail", Namespace="http://accipiens.com/Common")]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListResponse GetAutomatonReasonDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutomatonReasonDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutomatonReasonDataListResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListResponse> GetAutomatonReasonDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest request);
        
        // CODEGEN: Generating message contract since message GetAutUserStateDataListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutUserStateDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutUserStateDataListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.SVC_AutomatonsBasicLists.AcpDetail), Action="http://accipiens.com/AcpDetailError", Name="AcpDetail", Namespace="http://accipiens.com/Common")]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListResponse GetAutUserStateDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutUserStateDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutUserStateDataListResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListResponse> GetAutUserStateDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest request);
        
        // CODEGEN: Generating message contract since message GetAutomatonsAutUserStateDataListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutomatonsAutUserStateDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutomatonsAutUserStateDataListRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.SVC_AutomatonsBasicLists.AcpDetail), Action="http://accipiens.com/AcpDetailError", Name="AcpDetail", Namespace="http://accipiens.com/Common")]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListResponse GetAutomatonsAutUserStateDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accipiens.com/AutomatonsBasicLists/GetAutomatonsAutUserStateDataList", ReplyAction="http://accipiens.com/AutomatonsBasicLists/GetAutomatonsAutUserStateDataListRespon" +
            "se")]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListResponse> GetAutomatonsAutUserStateDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataWithForeign", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetDataWithForeignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://accipiens.com/Common")]
        public ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=1)]
        public string foreignReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=2)]
        public string id;
        
        public GetDataWithForeignRequest() {
        }
        
        public GetDataWithForeignRequest(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType, string foreignReference, string id) {
            this.SessionToken = SessionToken;
            this.listType = listType;
            this.foreignReference = foreignReference;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataWithForeignResponse", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetDataWithForeignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.CodeAbbreviation GetDataWithForeignResult;
        
        public GetDataWithForeignResponse() {
        }
        
        public GetDataWithForeignResponse(ConsoleApp1.SVC_AutomatonsBasicLists.CodeAbbreviation GetDataWithForeignResult) {
            this.GetDataWithForeignResult = GetDataWithForeignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataList", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetDataListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://accipiens.com/Common")]
        public ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsDataListId listType;
        
        public GetDataListRequest() {
        }
        
        public GetDataListRequest(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsDataListId listType) {
            this.SessionToken = SessionToken;
            this.listType = listType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataListResponse", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetDataListResult;
        
        public GetDataListResponse() {
        }
        
        public GetDataListResponse(ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetDataListResult) {
            this.GetDataListResult = GetDataListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetForeignDataList", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetForeignDataListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://accipiens.com/Common")]
        public ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=1)]
        public string foreignReference;
        
        public GetForeignDataListRequest() {
        }
        
        public GetForeignDataListRequest(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType, string foreignReference) {
            this.SessionToken = SessionToken;
            this.listType = listType;
            this.foreignReference = foreignReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetForeignDataListResponse", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetForeignDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetForeignDataListResult;
        
        public GetForeignDataListResponse() {
        }
        
        public GetForeignDataListResponse(ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetForeignDataListResult) {
            this.GetForeignDataListResult = GetForeignDataListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutomatonInternalCodeDataList", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutomatonInternalCodeDataListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://accipiens.com/Common")]
        public ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public string contextInternalCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=1)]
        public string contextAplPackageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=2)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonInternalCodeKind internalCodeKind;
        
        public GetAutomatonInternalCodeDataListRequest() {
        }
        
        public GetAutomatonInternalCodeDataListRequest(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, string contextInternalCode, string contextAplPackageId, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonInternalCodeKind internalCodeKind) {
            this.SessionToken = SessionToken;
            this.contextInternalCode = contextInternalCode;
            this.contextAplPackageId = contextAplPackageId;
            this.internalCodeKind = internalCodeKind;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutomatonInternalCodeDataListResponse", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutomatonInternalCodeDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonInternalCodeDataListResult;
        
        public GetAutomatonInternalCodeDataListResponse() {
        }
        
        public GetAutomatonInternalCodeDataListResponse(ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonInternalCodeDataListResult) {
            this.GetAutomatonInternalCodeDataListResult = GetAutomatonInternalCodeDataListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutomatonReasonDataList", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutomatonReasonDataListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://accipiens.com/Common")]
        public ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public long autTransitionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=1)]
        public long autUserStateId;
        
        public GetAutomatonReasonDataListRequest() {
        }
        
        public GetAutomatonReasonDataListRequest(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, long autTransitionId, long autUserStateId) {
            this.SessionToken = SessionToken;
            this.autTransitionId = autTransitionId;
            this.autUserStateId = autUserStateId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutomatonReasonDataListResponse", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutomatonReasonDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonReasonDataListResult;
        
        public GetAutomatonReasonDataListResponse() {
        }
        
        public GetAutomatonReasonDataListResponse(ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonReasonDataListResult) {
            this.GetAutomatonReasonDataListResult = GetAutomatonReasonDataListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutUserStateDataList", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutUserStateDataListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://accipiens.com/Common")]
        public ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public string autContextCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=1)]
        public long[] internalStateIdList;
        
        public GetAutUserStateDataListRequest() {
        }
        
        public GetAutUserStateDataListRequest(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, string autContextCode, long[] internalStateIdList) {
            this.SessionToken = SessionToken;
            this.autContextCode = autContextCode;
            this.internalStateIdList = internalStateIdList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutUserStateDataListResponse", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutUserStateDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutUserStateDataListResult;
        
        public GetAutUserStateDataListResponse() {
        }
        
        public GetAutUserStateDataListResponse(ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutUserStateDataListResult) {
            this.GetAutUserStateDataListResult = GetAutUserStateDataListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutomatonsAutUserStateDataList", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutomatonsAutUserStateDataListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://accipiens.com/Common")]
        public ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public long[] automatonIdList;
        
        public GetAutomatonsAutUserStateDataListRequest() {
        }
        
        public GetAutomatonsAutUserStateDataListRequest(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, long[] automatonIdList) {
            this.SessionToken = SessionToken;
            this.automatonIdList = automatonIdList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutomatonsAutUserStateDataListResponse", WrapperNamespace="http://accipiens.com", IsWrapped=true)]
    public partial class GetAutomatonsAutUserStateDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accipiens.com", Order=0)]
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonsAutUserStateDataListResult;
        
        public GetAutomatonsAutUserStateDataListResponse() {
        }
        
        public GetAutomatonsAutUserStateDataListResponse(ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonsAutUserStateDataListResult) {
            this.GetAutomatonsAutUserStateDataListResult = GetAutomatonsAutUserStateDataListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutomatonsBasicListsChannel : ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutomatonsBasicListsClient : System.ServiceModel.ClientBase<ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists>, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists {
        
        public AutomatonsBasicListsClient() {
        }
        
        public AutomatonsBasicListsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutomatonsBasicListsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutomatonsBasicListsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutomatonsBasicListsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignResponse ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetDataWithForeign(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest request) {
            return base.Channel.GetDataWithForeign(request);
        }
        
        public ConsoleApp1.SVC_AutomatonsBasicLists.CodeAbbreviation GetDataWithForeign(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType, string foreignReference, string id) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest();
            inValue.SessionToken = SessionToken;
            inValue.listType = listType;
            inValue.foreignReference = foreignReference;
            inValue.id = id;
            ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignResponse retVal = ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetDataWithForeign(inValue);
            return retVal.GetDataWithForeignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignResponse> ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetDataWithForeignAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest request) {
            return base.Channel.GetDataWithForeignAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignResponse> GetDataWithForeignAsync(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType, string foreignReference, string id) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetDataWithForeignRequest();
            inValue.SessionToken = SessionToken;
            inValue.listType = listType;
            inValue.foreignReference = foreignReference;
            inValue.id = id;
            return ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetDataWithForeignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListResponse ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest request) {
            return base.Channel.GetDataList(request);
        }
        
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetDataList(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsDataListId listType) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.listType = listType;
            ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListResponse retVal = ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetDataList(inValue);
            return retVal.GetDataListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListResponse> ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest request) {
            return base.Channel.GetDataListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListResponse> GetDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsDataListId listType) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.listType = listType;
            return ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetDataListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListResponse ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetForeignDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest request) {
            return base.Channel.GetForeignDataList(request);
        }
        
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetForeignDataList(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType, string foreignReference) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.listType = listType;
            inValue.foreignReference = foreignReference;
            ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListResponse retVal = ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetForeignDataList(inValue);
            return retVal.GetForeignDataListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListResponse> ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetForeignDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest request) {
            return base.Channel.GetForeignDataListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListResponse> GetForeignDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsForeignDataListId listType, string foreignReference) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetForeignDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.listType = listType;
            inValue.foreignReference = foreignReference;
            return ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetForeignDataListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListResponse ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutomatonInternalCodeDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest request) {
            return base.Channel.GetAutomatonInternalCodeDataList(request);
        }
        
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonInternalCodeDataList(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, string contextInternalCode, string contextAplPackageId, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonInternalCodeKind internalCodeKind) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.contextInternalCode = contextInternalCode;
            inValue.contextAplPackageId = contextAplPackageId;
            inValue.internalCodeKind = internalCodeKind;
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListResponse retVal = ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutomatonInternalCodeDataList(inValue);
            return retVal.GetAutomatonInternalCodeDataListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListResponse> ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutomatonInternalCodeDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest request) {
            return base.Channel.GetAutomatonInternalCodeDataListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListResponse> GetAutomatonInternalCodeDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, string contextInternalCode, string contextAplPackageId, ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonInternalCodeKind internalCodeKind) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonInternalCodeDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.contextInternalCode = contextInternalCode;
            inValue.contextAplPackageId = contextAplPackageId;
            inValue.internalCodeKind = internalCodeKind;
            return ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutomatonInternalCodeDataListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListResponse ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutomatonReasonDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest request) {
            return base.Channel.GetAutomatonReasonDataList(request);
        }
        
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonReasonDataList(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, long autTransitionId, long autUserStateId) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.autTransitionId = autTransitionId;
            inValue.autUserStateId = autUserStateId;
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListResponse retVal = ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutomatonReasonDataList(inValue);
            return retVal.GetAutomatonReasonDataListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListResponse> ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutomatonReasonDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest request) {
            return base.Channel.GetAutomatonReasonDataListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListResponse> GetAutomatonReasonDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, long autTransitionId, long autUserStateId) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonReasonDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.autTransitionId = autTransitionId;
            inValue.autUserStateId = autUserStateId;
            return ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutomatonReasonDataListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListResponse ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutUserStateDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest request) {
            return base.Channel.GetAutUserStateDataList(request);
        }
        
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutUserStateDataList(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, string autContextCode, long[] internalStateIdList) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.autContextCode = autContextCode;
            inValue.internalStateIdList = internalStateIdList;
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListResponse retVal = ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutUserStateDataList(inValue);
            return retVal.GetAutUserStateDataListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListResponse> ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutUserStateDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest request) {
            return base.Channel.GetAutUserStateDataListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListResponse> GetAutUserStateDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, string autContextCode, long[] internalStateIdList) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutUserStateDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.autContextCode = autContextCode;
            inValue.internalStateIdList = internalStateIdList;
            return ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutUserStateDataListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListResponse ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutomatonsAutUserStateDataList(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest request) {
            return base.Channel.GetAutomatonsAutUserStateDataList(request);
        }
        
        public ConsoleApp1.SVC_AutomatonsBasicLists.BasicList GetAutomatonsAutUserStateDataList(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, long[] automatonIdList) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.automatonIdList = automatonIdList;
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListResponse retVal = ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutomatonsAutUserStateDataList(inValue);
            return retVal.GetAutomatonsAutUserStateDataListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListResponse> ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists.GetAutomatonsAutUserStateDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest request) {
            return base.Channel.GetAutomatonsAutUserStateDataListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListResponse> GetAutomatonsAutUserStateDataListAsync(ConsoleApp1.SVC_AutomatonsBasicLists.SessionTokenWcfHeader SessionToken, long[] automatonIdList) {
            ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest inValue = new ConsoleApp1.SVC_AutomatonsBasicLists.GetAutomatonsAutUserStateDataListRequest();
            inValue.SessionToken = SessionToken;
            inValue.automatonIdList = automatonIdList;
            return ((ConsoleApp1.SVC_AutomatonsBasicLists.AutomatonsBasicLists)(this)).GetAutomatonsAutUserStateDataListAsync(inValue);
        }
    }
}
